id = "vitesse-theme-refined"
name = "Vitesse Theme Refined"
version = "0.3.1"
schema_version = 1
authors = ["Colin Lienard <contact@colin-lienard.fr>"]
description = "Vitesse Theme that better fits Zed"
repository = "https://github.com/colinlienard/zed-vitesse-theme-refined"
